version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./app:/usr/share/nginx/html
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/usr/share/nginx/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    container_name: db
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    volumes:
      - mysqldbvolume:/var/lib/mysql
      - .docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: book_store
      MYSQL_USER: user_test
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldbvolume:
    driver: local
